# Config file
# ---

# Data paths
PATHS:
  dataset_path: "./../../../data/raw/HAR/"
  resize_dataset_video_path: "./../../../data/processed/HAR/"
  output_csv_path: "./../../../data/processed/HAR/UCF"

# Model parameters
HYPERPARAMETERS:
  hidden_size: 1024
  lstm_layer: 2
  patch_size: 99
  num_classes: 6
  num_epochs: 1000
  batch_size: 256
  learning_rate: 0.001
  momentum: 0.9
  number_block: 1
  device: 'cuda'